name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      id: java
      uses: actions/setup-java@v2
      with: 
        java-version: '11'

    - name: Build and test Spring Boot application
      run: |
        ./mvnw test
