name: PMD Code Review

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Comprobar caché de PMD
      id: cache-check
      uses: actions/cache@v2
      with:
        path: pmd
        key: pmd

    - name: Descargar archivo de PMD
      if: steps.cache-check.outputs.cache-hit != 'true'
      run: |
        curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc3/pmd-dist-7.0.0-rc3-bin.zip
        unzip pmd.zip -d pmd
        rm pmd.zip

    - name: Ejecutar PMD
      run: |
        cd pmd/pmd-bin-7.0.0-rc3/bin
        ls
        pmd_command="./pmd check -d ../../../src/main/java -R ../../../pmdrules/rulesets/java/gardian.xml -f text"
        pmd_output=$(eval "$pmd_command")

    - name: Verificar problemas de PMD
        run: |
          echo "$pmd_output" | grep -q "ParseException"
          pmd_exit_code=$?
          if [ $pmd_exit_code -eq 0 ]; then
            echo >&2 -e "\e[1;31mFAILED\e[0m PMD encontró problemas en el código. Abortando push, corrija los cambios antes de realizar el siguiente push"
            echo "$pmd_output"
            exit 1
          else
            echo >&2 -e "\e[1;34mSUCCESS\e[0m PMD no encontró problemas en el código. \e[1;32mPush en proceso\e[0m"
            exit 0
          fi

    - name: Guardar caché de PMD
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: pmd
        key: pmd
