name: PMD Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Comprobar caché de PMD
      id: cache-check
      uses: actions/cache@v2
      with:
        path: pmd
        key: pmd

    - name: Descargar archivo de PMD
      if: steps.cache-check.outputs.cache-hit != 'true'
      run: |
        curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.39.1/pmd-bin-6.39.1.zip
        unzip pmd.zip -d pmd
        rm pmd.zip
        ls pmd

    - name: Ejecutar PMD
      run: |
        cd pmd/pmd-bin-6.39.1/bin
        ./run.sh pmd -d src/main/java -R ../PMD/rulesets/java/gardian.xml -f text

    - name: Guardar caché de PMD
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: pmd
        key: pmd
