name: PMD Code Review

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Comprobar caché de PMD
      id: cache-check
      uses: actions/cache@v2
      with:
        path: pmd
        key: pmd

    - name: Descargar archivo de PMD
      if: steps.cache-check.outputs.cache-hit != 'true'
      run: |
        curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc3/pmd-dist-7.0.0-rc3-bin.zip
        unzip pmd.zip -d pmd
        rm pmd.zip

    - name: Ejecutar PMD
      run: |
        cd pmd/pmd-bin-7.0.0-rc3/bin
        output=$(./pmd check -d ../../../src/main/java -R ../../../pmdrules/rulesets/java/gardian.xml -f text)
        if echo "$output" | grep -q "ERROR" || echo "$output" | grep -q "ParseException" ; then
          echo -e "\e[1;31mFAILED\e[0m PMD encontró un errores en tu codigo."
          exit 1
        else
          echo -e "\e[1;32mACCEPT\e[0m PMD no encontró errores."
        fi

    - name: Guardar caché de PMD
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: pmd
        key: pmd
