name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create branch backup
      run: |
        git branch backupBranch
        git checkout backupBranch
        git push origin backupBranch

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17.0.6'
        distribution: 'adopt'

    - name: Build and test Spring Boot application
      run: mvn test