name: Test Status

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  test-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get test result
      id: get-result
      run: |
        result=$(echo "${{ github.event.workflow_run.conclusion }}")

    - name: Get workflow run status
      id: get-status
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const runId = '${{ github.event.workflow_run.id }}';
          const { data: run } = await github.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: runId
          });
          console.log(run.status);
          return run.status;

    - name: Reset branch to previous commit
      if: steps.get-status.outputs.result == 'failure'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}