name: Test Status

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  test-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get test result
      id: get-result
      run: |
        result=$(echo "${{ github.event.workflow_run.conclusion }}")

    - name: Delete branch if tests failed
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const result = '${{ needs.build.outputs.result }}';
          if (result === 'failure') {
            const branchName = `refs/heads/${{ github.ref }}`;
            github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: branchName
            });
            console.log(`Deleted branch: ${branchName}`);
          }
